# Generated by Django 4.2.10 on 2024-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_image', models.ImageField(upload_to='doctor_images/')),
                ('doctor_timings', models.DateTimeField()),
                ('doctor_bio', models.CharField(max_length=255)),
                ('doctor_meet_link', models.URLField()),
            ],
        ),
    ]
