# Generated by Django 4.2.10 on 2024-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
