# Generated by Django 4.2.10 on 2024-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorprofile_doctor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor_meet_link',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_room_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
