# Generated by Django 5.0.2 on 2024-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0003_remove_doctorprofile_doctor_meet_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=20)),
                ("url", models.URLField(max_length=100)),
            ],
        ),
    ]
