# Generated by Django 5.0.2 on 2024-02-17 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0005_patientprofile"),
        ("social_django", "0015_rename_extra_data_new_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(max_length=200)),
                ("precaution", models.TextField()),
                ("medication", models.TextField()),
                (
                    "dr_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_django.usersocialauth",
                    ),
                ),
            ],
        ),
    ]
