# Generated by Django 5.0.2 on 2024-02-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0006_patientreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="doctor_bio",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="doctor_timings",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
