# Generated by Django 5.0.2 on 2024-02-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0007_remove_doctorprofile_doctor_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor_bio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
